#pragma once
#include "sc2api/sc2_interfaces.h"
#include "sc2api/sc2_agent.h"
#include "sc2api/sc2_map_info.h"

#include "sc2api/sc2_unit_filters.h"


namespace sc2
{

#define NEXUS UNIT_TYPEID::PROTOSS_NEXUS
#define PYLON UNIT_TYPEID::PROTOSS_PYLON
#define GATEWAY UNIT_TYPEID::PROTOSS_GATEWAY
#define WARP_GATE UNIT_TYPEID::PROTOSS_WARPGATE
#define ASSIMILATOR UNIT_TYPEID::PROTOSS_ASSIMILATOR
#define FORGE UNIT_TYPEID::PROTOSS_FORGE
#define CYBERCORE UNIT_TYPEID::PROTOSS_CYBERNETICSCORE
#define CANNON UNIT_TYPEID::PROTOSS_PHOTONCANNON
#define BATTERY UNIT_TYPEID::PROTOSS_SHIELDBATTERY
#define TWILIGHT UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL
#define TEMPLAR_ARCHIVES UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE
#define STARGATE UNIT_TYPEID::PROTOSS_STARGATE
#define FLEET_BEACON UNIT_TYPEID::PROTOSS_FLEETBEACON
#define DARK_SHRINE UNIT_TYPEID::PROTOSS_DARKSHRINE
#define ROBO UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY
#define ROBO_BAY UNIT_TYPEID::PROTOSS_ROBOTICSBAY
#define PROBE UNIT_TYPEID::PROTOSS_PROBE
#define ZEALOT UNIT_TYPEID::PROTOSS_ZEALOT
#define STALKER UNIT_TYPEID::PROTOSS_STALKER
#define SENTRY UNIT_TYPEID::PROTOSS_SENTRY
#define ADEPT UNIT_TYPEID::PROTOSS_ADEPT
#define HIGH_TEMPLAR UNIT_TYPEID::PROTOSS_HIGHTEMPLAR
#define DARK_TEMPLAR UNIT_TYPEID::PROTOSS_DARKTEMPLAR
#define IMMORTAL UNIT_TYPEID::PROTOSS_IMMORTAL
#define COLOSSUS UNIT_TYPEID::PROTOSS_COLOSSUS
#define DISRUPTER UNIT_TYPEID::PROTOSS_DISRUPTOR
#define ARCHON UNIT_TYPEID::PROTOSS_ARCHON
#define OBSERVER UNIT_TYPEID::PROTOSS_OBSERVER
#define OBSERVER_SIEGED UNIT_TYPEID::PROTOSS_OBSERVERSIEGEMODE
#define PRISM UNIT_TYPEID::PROTOSS_WARPPRISM
#define PRISM_SIEGED UNIT_TYPEID::PROTOSS_WARPPRISMPHASING
#define PHOENIX UNIT_TYPEID::PROTOSS_PHOENIX
#define VOID_RAY UNIT_TYPEID::PROTOSS_VOIDRAY
#define ORACLE UNIT_TYPEID::PROTOSS_ORACLE
#define CARRIER UNIT_TYPEID::PROTOSS_CARRIER
#define TEMPEST UNIT_TYPEID::PROTOSS_TEMPEST
#define MOTHERSHIP UNIT_TYPEID::PROTOSS_MOTHERSHIP


#define COMMAND_CENTER UNIT_TYPEID::TERRAN_COMMANDCENTER
#define COMMAND_CENTER_FLYING UNIT_TYPEID::TERRAN_COMMANDCENTERFLYING
#define PLANETARY UNIT_TYPEID::TERRAN_PLANETARYFORTRESS
#define ORBITAL UNIT_TYPEID::TERRAN_ORBITALCOMMAND
#define ORBITAL_FLYING UNIT_TYPEID::TERRAN_ORBITALCOMMANDFLYING
#define SUPPLY_DEPOT UNIT_TYPEID::TERRAN_SUPPLYDEPOT
#define SUPPLY_DEPOT_LOWERED UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED
#define REFINERY UNIT_TYPEID::TERRAN_REFINERY
#define BARRACKS UNIT_TYPEID::TERRAN_BARRACKS
#define BARRACKS_FLYING UNIT_TYPEID::TERRAN_BARRACKSFLYING
#define ENGINEERING_BAY UNIT_TYPEID::TERRAN_ENGINEERINGBAY
#define BUNKER UNIT_TYPEID::TERRAN_BUNKER
#define SENSOR_TOWER UNIT_TYPEID::TERRAN_SENSORTOWER
#define MISSILE_TURRET UNIT_TYPEID::TERRAN_MISSILETURRET
#define FACTORY UNIT_TYPEID::TERRAN_FACTORY
#define FACTORY_FLYING UNIT_TYPEID::TERRAN_FACTORYFLYING
#define GHOST_ACADEMY UNIT_TYPEID::TERRAN_GHOSTACADEMY
#define STARPORT UNIT_TYPEID::TERRAN_STARPORT
#define STARPORT_FLYING UNIT_TYPEID::TERRAN_STARPORTFLYING
#define ARMORY UNIT_TYPEID::TERRAN_ARMORY
#define FUSION_CORE UNIT_TYPEID::TERRAN_FUSIONCORE
#define TECH_LAB UNIT_TYPEID::TERRAN_TECHLAB
#define REACTOR UNIT_TYPEID::TERRAN_REACTOR
#define BARRACKS_TECH_LAB UNIT_TYPEID::TERRAN_BARRACKSTECHLAB
#define BARRACKS_REACTOR UNIT_TYPEID::TERRAN_BARRACKSREACTOR
#define FACTORY_TECH_LAB UNIT_TYPEID::TERRAN_FACTORYTECHLAB
#define FACTORY_REACTOR UNIT_TYPEID::TERRAN_FACTORYREACTOR
#define STARPORT_TECH_LAB UNIT_TYPEID::TERRAN_STARPORTTECHLAB
#define STARPORT_REACTOR UNIT_TYPEID::TERRAN_STARPORTREACTOR
#define SCV UNIT_TYPEID::TERRAN_SCV
#define MULE UNIT_TYPEID::TERRAN_MULE
#define MARINE UNIT_TYPEID::TERRAN_MARINE
#define MARAUDER UNIT_TYPEID::TERRAN_MARAUDER
#define REAPER UNIT_TYPEID::TERRAN_REAPER
#define GHOST UNIT_TYPEID::TERRAN_GHOST
#define HELLION UNIT_TYPEID::TERRAN_HELLION
#define HELLBAT UNIT_TYPEID::TERRAN_HELLIONTANK
#define SIEGE_TANK UNIT_TYPEID::TERRAN_SIEGETANK
#define SIEGE_TANK_SIEGED UNIT_TYPEID::TERRAN_SIEGETANKSIEGED
#define CYCLONE UNIT_TYPEID::TERRAN_CYCLONE
#define THOR_AOE UNIT_TYPEID::TERRAN_THOR
#define THOR_AP UNIT_TYPEID::TERRAN_THORAP
#define WIDOW_MINE UNIT_TYPEID::TERRAN_WIDOWMINE
#define AUTO_TURRET UNIT_TYPEID::TERRAN_AUTOTURRET
#define VIKING UNIT_TYPEID::TERRAN_VIKINGFIGHTER
#define VIKING_LANDED UNIT_TYPEID::TERRAN_VIKINGASSAULT
#define MEDIVAC UNIT_TYPEID::TERRAN_MEDIVAC
#define LIBERATOR UNIT_TYPEID::TERRAN_LIBERATOR
#define LIBERATOR_SIEGED UNIT_TYPEID::TERRAN_LIBERATORAG
#define RAVEN UNIT_TYPEID::TERRAN_RAVEN
#define BANSHEE UNIT_TYPEID::TERRAN_BANSHEE
#define BATTLECRUISER UNIT_TYPEID::TERRAN_BATTLECRUISER


}