#pragma once
#include "sc2api/sc2_unit_filters.h"

#include <vector>

namespace sc2
{


#define FRAME_TIME 22.4f
#define MAX_WORKERS 70
#define VERY_CLOSE_RANGE 2.0f
#define CLOSE_RANGE 5.0f
#define MEDIUM_RANGE 10.0f
#define LONG_RANGE 15.0f
#define VERY_LONG_RANGE 20.0f

#define OGA_LOSING_HARD -100
#define OGA_LOSING -50
#define OGA_LOSING_SLIGHTLY -20

#define NEXUS UNIT_TYPEID::PROTOSS_NEXUS
#define PYLON UNIT_TYPEID::PROTOSS_PYLON
#define GATEWAY UNIT_TYPEID::PROTOSS_GATEWAY
#define WARP_GATE UNIT_TYPEID::PROTOSS_WARPGATE
#define ASSIMILATOR UNIT_TYPEID::PROTOSS_ASSIMILATOR
#define ASSIMILATOR_RICH UNIT_TYPEID::PROTOSS_ASSIMILATORRICH
#define FORGE UNIT_TYPEID::PROTOSS_FORGE
#define CYBERCORE UNIT_TYPEID::PROTOSS_CYBERNETICSCORE
#define CANNON UNIT_TYPEID::PROTOSS_PHOTONCANNON
#define BATTERY UNIT_TYPEID::PROTOSS_SHIELDBATTERY
#define TWILIGHT UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL
#define TEMPLAR_ARCHIVE UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE
#define STARGATE UNIT_TYPEID::PROTOSS_STARGATE
#define FLEET_BEACON UNIT_TYPEID::PROTOSS_FLEETBEACON
#define DARK_SHRINE UNIT_TYPEID::PROTOSS_DARKSHRINE
#define ROBO UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY
#define ROBO_BAY UNIT_TYPEID::PROTOSS_ROBOTICSBAY
#define PROBE UNIT_TYPEID::PROTOSS_PROBE
#define ZEALOT UNIT_TYPEID::PROTOSS_ZEALOT
#define STALKER UNIT_TYPEID::PROTOSS_STALKER
#define SENTRY UNIT_TYPEID::PROTOSS_SENTRY
#define ADEPT UNIT_TYPEID::PROTOSS_ADEPT
#define ADEPT_SHADE UNIT_TYPEID::PROTOSS_ADEPTPHASESHIFT
#define HIGH_TEMPLAR UNIT_TYPEID::PROTOSS_HIGHTEMPLAR
#define DARK_TEMPLAR UNIT_TYPEID::PROTOSS_DARKTEMPLAR
#define IMMORTAL UNIT_TYPEID::PROTOSS_IMMORTAL
#define COLOSSUS UNIT_TYPEID::PROTOSS_COLOSSUS
#define DISRUPTOR UNIT_TYPEID::PROTOSS_DISRUPTOR
#define ARCHON UNIT_TYPEID::PROTOSS_ARCHON
#define OBSERVER UNIT_TYPEID::PROTOSS_OBSERVER
#define OBSERVER_SIEGED UNIT_TYPEID::PROTOSS_OBSERVERSIEGEMODE
#define PRISM UNIT_TYPEID::PROTOSS_WARPPRISM
#define PRISM_SIEGED UNIT_TYPEID::PROTOSS_WARPPRISMPHASING
#define PHOENIX UNIT_TYPEID::PROTOSS_PHOENIX
#define VOID_RAY UNIT_TYPEID::PROTOSS_VOIDRAY
#define ORACLE UNIT_TYPEID::PROTOSS_ORACLE
#define CARRIER UNIT_TYPEID::PROTOSS_CARRIER
#define TEMPEST UNIT_TYPEID::PROTOSS_TEMPEST
#define MOTHERSHIP UNIT_TYPEID::PROTOSS_MOTHERSHIP


#define COMMAND_CENTER UNIT_TYPEID::TERRAN_COMMANDCENTER
#define COMMAND_CENTER_FLYING UNIT_TYPEID::TERRAN_COMMANDCENTERFLYING
#define PLANETARY UNIT_TYPEID::TERRAN_PLANETARYFORTRESS
#define ORBITAL UNIT_TYPEID::TERRAN_ORBITALCOMMAND
#define ORBITAL_FLYING UNIT_TYPEID::TERRAN_ORBITALCOMMANDFLYING
#define SUPPLY_DEPOT UNIT_TYPEID::TERRAN_SUPPLYDEPOT
#define SUPPLY_DEPOT_LOWERED UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED
#define REFINERY UNIT_TYPEID::TERRAN_REFINERY
#define REFINERY_RICH UNIT_TYPEID::TERRAN_REFINERYRICH
#define BARRACKS UNIT_TYPEID::TERRAN_BARRACKS
#define BARRACKS_FLYING UNIT_TYPEID::TERRAN_BARRACKSFLYING
#define ENGINEERING_BAY UNIT_TYPEID::TERRAN_ENGINEERINGBAY
#define BUNKER UNIT_TYPEID::TERRAN_BUNKER
#define NEOSTEEL_BUNKER UNIT_TYPEID::TERRAN_PREVIEWBUNKERUPGRADED
#define SENSOR_TOWER UNIT_TYPEID::TERRAN_SENSORTOWER
#define MISSILE_TURRET UNIT_TYPEID::TERRAN_MISSILETURRET
#define FACTORY UNIT_TYPEID::TERRAN_FACTORY
#define FACTORY_FLYING UNIT_TYPEID::TERRAN_FACTORYFLYING
#define GHOST_ACADEMY UNIT_TYPEID::TERRAN_GHOSTACADEMY
#define STARPORT UNIT_TYPEID::TERRAN_STARPORT
#define STARPORT_FLYING UNIT_TYPEID::TERRAN_STARPORTFLYING
#define ARMORY UNIT_TYPEID::TERRAN_ARMORY
#define FUSION_CORE UNIT_TYPEID::TERRAN_FUSIONCORE
#define TECH_LAB UNIT_TYPEID::TERRAN_TECHLAB
#define REACTOR UNIT_TYPEID::TERRAN_REACTOR
#define BARRACKS_TECH_LAB UNIT_TYPEID::TERRAN_BARRACKSTECHLAB
#define BARRACKS_REACTOR UNIT_TYPEID::TERRAN_BARRACKSREACTOR
#define FACTORY_TECH_LAB UNIT_TYPEID::TERRAN_FACTORYTECHLAB
#define FACTORY_REACTOR UNIT_TYPEID::TERRAN_FACTORYREACTOR
#define STARPORT_TECH_LAB UNIT_TYPEID::TERRAN_STARPORTTECHLAB
#define STARPORT_REACTOR UNIT_TYPEID::TERRAN_STARPORTREACTOR
#define SCV UNIT_TYPEID::TERRAN_SCV
#define MULE UNIT_TYPEID::TERRAN_MULE
#define MARINE UNIT_TYPEID::TERRAN_MARINE
#define MARAUDER UNIT_TYPEID::TERRAN_MARAUDER
#define REAPER UNIT_TYPEID::TERRAN_REAPER
#define GHOST UNIT_TYPEID::TERRAN_GHOST
#define HELLION UNIT_TYPEID::TERRAN_HELLION
#define HELLBAT UNIT_TYPEID::TERRAN_HELLIONTANK
#define SIEGE_TANK UNIT_TYPEID::TERRAN_SIEGETANK
#define SIEGE_TANK_SIEGED UNIT_TYPEID::TERRAN_SIEGETANKSIEGED
#define CYCLONE UNIT_TYPEID::TERRAN_CYCLONE
#define THOR_AOE UNIT_TYPEID::TERRAN_THOR
#define THOR_AP UNIT_TYPEID::TERRAN_THORAP
#define WIDOW_MINE UNIT_TYPEID::TERRAN_WIDOWMINE
#define WIDOW_MINE_BURROWED UNIT_TYPEID::TERRAN_WIDOWMINEBURROWED
#define AUTO_TURRET UNIT_TYPEID::TERRAN_AUTOTURRET
#define VIKING UNIT_TYPEID::TERRAN_VIKINGFIGHTER
#define VIKING_LANDED UNIT_TYPEID::TERRAN_VIKINGASSAULT
#define MEDIVAC UNIT_TYPEID::TERRAN_MEDIVAC
#define LIBERATOR UNIT_TYPEID::TERRAN_LIBERATOR
#define LIBERATOR_SIEGED UNIT_TYPEID::TERRAN_LIBERATORAG
#define RAVEN UNIT_TYPEID::TERRAN_RAVEN
#define BANSHEE UNIT_TYPEID::TERRAN_BANSHEE
#define BATTLECRUISER UNIT_TYPEID::TERRAN_BATTLECRUISER


#define LARVA UNIT_TYPEID::ZERG_LARVA
#define EGG UNIT_TYPEID::ZERG_EGG
#define DRONE UNIT_TYPEID::ZERG_DRONE
#define DRONE_BURROWED UNIT_TYPEID::ZERG_DRONEBURROWED
#define QUEEN UNIT_TYPEID::ZERG_QUEEN
#define QUEEN_BURROWED UNIT_TYPEID::ZERG_QUEENBURROWED
#define ZERGLING UNIT_TYPEID::ZERG_ZERGLING
#define ZERGLING_BURROWED UNIT_TYPEID::ZERG_ZERGLINGBURROWED
#define BANELING_EGG UNIT_TYPEID::ZERG_BANELINGCOCOON
#define BANELING UNIT_TYPEID::ZERG_BANELING
#define BANELING_BURROWED UNIT_TYPEID::ZERG_BANELINGBURROWED
#define ROACH UNIT_TYPEID::ZERG_ROACH
#define ROACH_BURROWED UNIT_TYPEID::ZERG_ROACHBURROWED
#define RAVAGER_EGG UNIT_TYPEID::ZERG_RAVAGERCOCOON
#define RAVAGER UNIT_TYPEID::ZERG_RAVAGER
#define RAVAGER_BURROWED UNIT_TYPEID::RAVAGERBURROWED
#define HYDRA UNIT_TYPEID::ZERG_HYDRALISK
#define HYDRA_BURROWED UNIT_TYPEID::ZERG_HYDRALISKBURROWED
#define LURKER_EGG UNIT_TYPEID::ZERG_LURKERMPEGG
#define LURKER UNIT_TYPEID::ZERG_LURKERMP
#define LURKER_BURROWED UNIT_TYPEID::ZERG_LURKERMPBURROWED
#define INFESTOR UNIT_TYPEID::ZERG_INFESTOR
#define INFESTOR_BURROWED UNIT_TYPEID::ZERG_INFESTORBURROWED
#define SWARMHOST UNIT_TYPEID::ZERG_SWARMHOSTMP
#define SWARMHOST_BURROWED UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP
#define ULTRALISK UNIT_TYPEID::ZERG_ULTRALISK
#define ULTRALISK_BURROWED UNIT_TYPEID::ZERG_ULTRALISKBURROWED
#define LOCUST UNIT_TYPEID::ZERG_LOCUSTMP
#define LOCUST_FLYING UNIT_TYPEID::ZERG_LOCUSTMPFLYING
#define BROODLING UNIT_TYPEID::ZERG_BROODLING
#define CHANGELING UNIT_TYPEID::ZERG_CHANGELING
#define CHANGELING_ZEALOT UNIT_TYPEID::ZERG_CHANGELINGZEALOT
#define NYDUS_WORM UNIT_TYPEID::ZERG_NYDUSCANAL
#define OVERLORD UNIT_TYPEID::ZERG_OVERLORD
#define DROPPERLORD_EGG UNIT_TYPEID::ZERG_TRANSPORTOVERLORDCOCOON
#define DROPPERLORD UNIT_TYPEID::ZERG_OVERLORDTRANSPORT
#define OVERSEER_EGG UNIT_TYPEID::ZERG_OVERLORDCOCOON
#define OVERSEER UNIT_TYPEID::ZERG_OVERSEER
#define OVERSEER_SIEGED UNIT_TYPEID::ZERG_OVERSEERSIEGEMODE
#define MUTALISK UNIT_TYPEID::ZERG_MUTALISK
#define CORRUPTER UNIT_TYPEID::ZERG_CORRUPTOR
#define BROOD_LORD_EGG UNIT_TYPEID::ZERG_BROODLORDCOCOON
#define BROOD_LORD UNIT_TYPEID::ZERG_BROODLORD
#define VIPER UNIT_TYPEID::ZERG_VIPER
#define HATCHERY UNIT_TYPEID::ZERG_HATCHERY
#define LAIR UNIT_TYPEID::ZERG_LAIR
#define HIVE UNIT_TYPEID::ZERG_HIVE
#define SPINE_CRAWLER UNIT_TYPEID::ZERG_SPINECRAWLER
#define SPINE_CRAWLER_UPROOTED UNIT_TYPEID::ZERG_SPINECRAWLERUPROOTED
#define SPORE_CRAWLER UNIT_TYPEID::ZERG_SPORECRAWLER
#define SPORE_CRAWLER_UPROOTED UNIT_TYPEID::ZERG_SPORECRAWLERUPROOTED
#define SPAWNING_POOL UNIT_TYPEID::ZERG_SPAWNINGPOOL
#define ROACH_WARREN UNIT_TYPEID::ZERG_ROACHWARREN
#define EVO_CHAMBER UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER
#define EXTRACTOR UNIT_TYPEID::ZERG_EXTRACTOR
#define EXTRACTOR_RICH UNIT_TYPEID::ZERG_EXTRACTORRICH
#define BANELING_NEST UNIT_TYPEID::ZERG_BANELINGNEST
#define HYDRA_DEN UNIT_TYPEID::ZERG_HYDRALISKDEN
#define LURKER_DEN UNIT_TYPEID::ZERG_LURKERDENMP
#define INFESTATION_PIT UNIT_TYPEID::ZERG_INFESTATIONPIT
#define NYDUS UNIT_TYPEID::ZERG_NYDUSNETWORK
#define SPIRE UNIT_TYPEID::ZERG_SPIRE
#define GREATER_SPIRE UNIT_TYPEID::ZERG_GREATERSPIRE
#define ULTRALISK_CAVERN UNIT_TYPEID::ZERG_ULTRALISKCAVERN
#define CREEP_TUMOR_1 UNIT_TYPEID::ZERG_CREEPTUMOR
#define CREEP_TUMOR_2 UNIT_TYPEID::ZERG_CREEPTUMORBURROWED
#define CREEP_TUMOR_3 UNIT_TYPEID::ZERG_CREEPTUMORQUEEN

#define FORCEFIELD UNIT_TYPEID::NEUTRAL_FORCEFIELD

#define U_INVALID UPGRADE_ID::INVALID
#define U_WARPGATE UPGRADE_ID::WARPGATERESEARCH
#define U_BLINK UPGRADE_ID::BLINKTECH
#define U_CHARGE UPGRADE_ID::CHARGE
#define U_GLAIVES UPGRADE_ID::ADEPTPIERCINGATTACK
#define U_DT_BLINK UPGRADE_ID::DARKTEMPLARBLINKUPGRADE
#define U_STORM UPGRADE_ID::PSISTORMTECH
#define U_THERMAL_LANCE UPGRADE_ID::EXTENDEDTHERMALLANCE
#define U_PRISM_SPEED UPGRADE_ID::GRAVITICDRIVE
#define U_OBS_SPEED UPGRADE_ID::GRAVITICTHRUSTERS
#define U_PHOENIX_RANGE UPGRADE_ID::ANIONPULSECRYSTALS
#define U_FLUX_VANES UPGRADE_ID::VOIDRAYSPEEDUPGRADE
#define U_TECTONIC_DESTABALIZERS UPGRADE_ID::TEMPESTGROUNDATTACKUPGRADE
#define U_GROUND_WEAPONS_1 UPGRADE_ID::PROTOSSGROUNDWEAPONSLEVEL1
#define U_GROUND_WEAPONS_2 UPGRADE_ID::PROTOSSGROUNDWEAPONSLEVEL2
#define U_GROUND_WEAPONS_3 UPGRADE_ID::PROTOSSGROUNDWEAPONSLEVEL3
#define U_GROUND_ARMOR_1 UPGRADE_ID::PROTOSSGROUNDARMORSLEVEL1
#define U_GROUND_ARMOR_2 UPGRADE_ID::PROTOSSGROUNDARMORSLEVEL2
#define U_GROUND_ARMOR_3 UPGRADE_ID::PROTOSSGROUNDARMORSLEVEL3
#define U_SHIELDS_1 UPGRADE_ID::PROTOSSSHIELDSLEVEL1
#define U_SHIELDS_2 UPGRADE_ID::PROTOSSSHIELDSLEVEL2
#define U_SHIELDS_3 UPGRADE_ID::PROTOSSSHIELDSLEVEL3
#define U_AIR_WEAPONS_1 UPGRADE_ID::PROTOSSAIRWEAPONSLEVEL1
#define U_AIR_WEAPONS_2 UPGRADE_ID::PROTOSSAIRWEAPONSLEVEL2
#define U_AIR_WEAPONS_3 UPGRADE_ID::PROTOSSAIRWEAPONSLEVEL3
#define U_AIR_ARMOR_1 UPGRADE_ID::PROTOSSAIRARMORSLEVEL1
#define U_AIR_ARMOR_2 UPGRADE_ID::PROTOSSAIRARMORSLEVEL2
#define U_AIR_ARMOR_3 UPGRADE_ID::PROTOSSAIRARMORSLEVEL3

#define A_MOVE ABILITY_ID::GENERAL_MOVE
#define A_STOP ABILITY_ID::STOP
#define A_HOLD_POSITION ABILITY_ID::GENERAL_HOLDPOSITION
#define A_ATTACK ABILITY_ID::ATTACK
#define A_SMART ABILITY_ID::SMART
#define A_CHRONO ABILITY_ID::EFFECT_CHRONOBOOSTENERGYCOST
#define A_NEXUS_RECALL ABILITY_ID::EFFECT_MASSRECALL_NEXUS
#define A_ENERGY_RECHARGE 4126
#define A_ORACLE_BEAM_ON ABILITY_ID::BEHAVIOR_PULSARBEAMON
#define A_ORACLE_BEAM_OFF ABILITY_ID::BEHAVIOR_PULSARBEAMOFF
#define A_REVELATION ABILITY_ID::EFFECT_ORACLEREVELATION
#define A_BLINK ABILITY_ID::EFFECT_BLINK
#define A_FORCEFIELD ABILITY_ID::EFFECT_FORCEFIELD
#define A_GUARDIAN_SHIELD ABILITY_ID::EFFECT_GUARDIANSHIELD
#define A_SHADE ABILITY_ID::EFFECT_ADEPTPHASESHIFT
#define A_CANCEL_SHADE ABILITY_ID::CANCEL_ADEPTPHASESHIFT
#define A_UNLOAD_AT ABILITY_ID::UNLOADALLAT
#define A_GATHER_RESOURCE ABILITY_ID::HARVEST_GATHER
#define A_RETURN_RESOURCE ABILITY_ID::HARVEST_RETURN
#define A_CANCEL_BUILDING ABILITY_ID::CANCEL
#define A_CANCEL_PRODUCTION ABILITY_ID::CANCEL_LAST
#define A_PRISM_PHASING_MODE ABILITY_ID::MORPH_WARPPRISMPHASINGMODE
#define A_PRISM_TRANSPORT_MODE ABILITY_ID::MORPH_WARPPRISMTRANSPORTMODE

#define A_RESEARCH_SHIELDS ABILITY_ID::RESEARCH_PROTOSSSHIELDS
#define A_RESEARCH_GROUND_WEAPONS ABILITY_ID::RESEARCH_PROTOSSGROUNDWEAPONS
#define A_RESEARCH_GROUND_ARMOR ABILITY_ID::RESEARCH_PROTOSSGROUNDARMOR
#define A_RESEARCH_AIR_WEAPONS ABILITY_ID::RESEARCH_PROTOSSAIRWEAPONS
#define A_RESEARCH_AIR_ARMOR ABILITY_ID::RESEARCH_PROTOSSAIRARMOR



#define CD_CHARGE 7.0f
#define CD_STALKER_BLINK 7.0f
#define CD_SHADE 11.f
#define CD_STORM 1.43f
#define CD_DT_BLINK 14.0f
#define CD_IMMORTAL_BARRIER 32.0f
#define CD_PURIFICATION_NOVA 21.4f
#define CD_PRISMATIC_ALIGNMENT 42.9f
#define CD_REVELATION 10.0f
#define CD_TIME_WARP 60.0f
#define CD_MOTHERSHIP_RECALL 89.0f
#define CD_MOTHERSHIP_CLOAK 50.0f
#define CD_NEXUS_RECALL 130.0f
#define CD_ENERGY_RECHARGE 60.0f

#define DURATION_GUARDIAN_SHIELD 12.86f
#define DURATION_FORCEFIELD 11.0f
#define DURATION_SHADE 7.0f
#define DURATION_STORM 2.85f
#define DURATION_IMMORTAL_BARRIER 2.0f
#define DURATION_PURIFICATION_NOVA 2.1f
#define DURATION_PRISMATIC_ALIGNMENT 14.3f
#define DURATION_REVELATION 20.0f
#define DURATION_STASIS_WARD 170.0f
#define DURATION_TIME_WARP 7.0f
#define DURATION_MOTHERSHIP_CLOAK 20.0f

#define RANGE_BLINK 8.0f
#define RANGE_GUARDIAN_SHIELD 4.5f
#define RANGE_FORCEFIELD 9.0f
#define RANGE_FEEDBACK 10.0f
#define RANGE_STORM 9.0f
#define RANGE_DT_BLINK 8.0f
#define RANGE_REVELATION 9.0f
#define RANGE_STASIS_WARD 6.0f
#define RANGE_TIME_WARP 9.0f
#define RANGE_ENERGY_RECHARGE 12.55f // TODO check
#define RANGE_PRISM_PICKUP  5.0f // TODO if counts radius of unit

#define SIZE_FORCEFIELD 1.7f
#define SIZE_STORM 1.5f
#define SIZE_PURIFICATION_NOVA 1.5f
#define SIZE_REVELATION 6.0f
#define SIZE_STASIS_WARD 4.0f
#define SIZE_TIME_WARP 3.75f
#define SIZE_MOTHERSHIP_RECALL 5.0f
#define SIZE_MOTHERSHIP_CLOAK 5.0f
#define SIZE_NEXUS_RECALL 2.5f

#define ENERGY_COST_FORCEFIELD 50
#define ENERGY_COST_GUARDIAN_SHIELD 75
#define ENERGY_COST_FEEDBACK 50
#define ENERGY_COST_STORM 75
#define ENERGY_COST_GRAVITON_BEAM 50
#define ENERGY_COST_REVELATION 25
#define ENERGY_COST_PULSAR_BEAM 25
#define ENERGY_COST_STASIS_WARD 50
#define ENERGY_COST_NEXUS_RECALL 50
#define ENERGY_COST_ENERGY_RECHARGE 50
#define ENERGY_COST_CHRONO 50

#define DURATION_SPAWN_LARVA 29
#define CD_GENERATE_LARVA 11
#define RANGE_MEDIVAC_HEAL 4
#define HEAL_RATE_MEDIVAC 12.6f

#define B_LOCK_ON BUFF_ID::LOCKON
#define CORROSIVE_BILE_DAMAGE 60


const std::vector<std::vector<UNIT_TYPEID>> TERRAN_PRIO = { {SIEGE_TANK_SIEGED},
															{SIEGE_TANK},
															{WIDOW_MINE},
															{VIKING, LIBERATOR_SIEGED},
															{RAVEN},
															{MEDIVAC},
															{CYCLONE},
															{GHOST},
															{MARINE, MARAUDER, REAPER, HELLION, HELLBAT, THOR_AP, THOR_AOE, VIKING_LANDED, BANSHEE, BATTLECRUISER, LIBERATOR},
															{SCV, MULE},
															{BUNKER},
															{PLANETARY},
															{MISSILE_TURRET},
															{BARRACKS_REACTOR, FACTORY_REACTOR, STARPORT_REACTOR},
															{BARRACKS_TECH_LAB, FACTORY_TECH_LAB, STARPORT_TECH_LAB},
															{REACTOR, TECH_LAB},
															{SUPPLY_DEPOT, SUPPLY_DEPOT_LOWERED},
															{COMMAND_CENTER, ORBITAL} };

const std::vector<std::vector<UNIT_TYPEID>> ZERG_PRIO = { {LURKER_BURROWED},
															{LURKER, LURKER_EGG},
															{INFESTOR, INFESTOR_BURROWED, VIPER},
															{BROOD_LORD, BROOD_LORD_EGG},
															{DROPPERLORD},
															{BANELING_EGG, BANELING, BANELING_BURROWED},
															{MUTALISK, CORRUPTER},
															{QUEEN, QUEEN_BURROWED, ZERGLING, ZERGLING_BURROWED, ROACH, ROACH_BURROWED, HYDRA, HYDRA_BURROWED, ULTRALISK, ULTRALISK_BURROWED},
															{SPINE_CRAWLER},
															{SPORE_CRAWLER},
															{SPINE_CRAWLER_UPROOTED, SPORE_CRAWLER_UPROOTED},
															{SWARMHOST, SWARMHOST_BURROWED},
															{DRONE, DRONE_BURROWED},
															{NYDUS_WORM},
															{LOCUST, LOCUST_FLYING, BROODLING},
															{OVERSEER, OVERSEER_SIEGED, OVERSEER_EGG},
															{OVERLORD},
															{HATCHERY, LAIR, HIVE},
															{SPAWNING_POOL, ROACH_WARREN, BANELING_NEST, HYDRA_DEN, LURKER_DEN, INFESTATION_PIT, NYDUS, SPIRE, GREATER_SPIRE, ULTRALISK_CAVERN},
															{EVO_CHAMBER, EXTRACTOR},
															{CREEP_TUMOR_1, CREEP_TUMOR_2, CREEP_TUMOR_3},
															{CHANGELING, CHANGELING_ZEALOT},
															{LARVA, EGG}, };

const std::vector<std::vector<UNIT_TYPEID>> PROTOSS_PRIO = { {BATTERY},
															{PRISM, PRISM_SIEGED},
															{DISRUPTOR},
															{HIGH_TEMPLAR, SENTRY},
															{PHOENIX, VOID_RAY, IMMORTAL},
															{ZEALOT, STALKER, ADEPT, DARK_TEMPLAR, COLOSSUS, ARCHON, ORACLE, CARRIER, TEMPEST, MOTHERSHIP},
															{PROBE},
															{OBSERVER, OBSERVER_SIEGED},
															{PYLON},
															{CANNON},
															{NEXUS},
															{GATEWAY, WARP_GATE, FORGE, CYBERCORE, TWILIGHT, TEMPLAR_ARCHIVE, STARGATE, FLEET_BEACON, DARK_SHRINE, ROBO, ROBO_BAY},
															{ASSIMILATOR} };

const std::vector<UNIT_TYPEID> ALL_ARMY_UNITS = { ZEALOT, ADEPT, STALKER, SENTRY, DARK_TEMPLAR, HIGH_TEMPLAR, ARCHON, 
												IMMORTAL, PRISM, PRISM_SIEGED, OBSERVER, OBSERVER_SIEGED, COLOSSUS, DISRUPTOR, 
												PHOENIX, VOID_RAY, ORACLE, CARRIER, TEMPEST, MOTHERSHIP };

const std::vector<UNIT_TYPEID> BURROWED_UNIT_TYPES = { RAVAGER_BURROWED, WIDOW_MINE_BURROWED, BANELING_BURROWED, DRONE_BURROWED,
														HYDRA_BURROWED, INFESTOR_BURROWED, LURKER_BURROWED, QUEEN_BURROWED,
														ROACH_BURROWED, SWARMHOST_BURROWED, ULTRALISK_BURROWED, ZERGLING_BURROWED };

const std::vector<UNIT_TYPEID> HIT_SCAN_UNIT_TYPES = { PROBE, ZEALOT, SENTRY, DARK_TEMPLAR, IMMORTAL, COLOSSUS, ARCHON, ORACLE, VOID_RAY, MOTHERSHIP,
														SCV, MARINE, REAPER, GHOST, HELLION, HELLBAT, SIEGE_TANK, SIEGE_TANK_SIEGED, THOR_AOE, THOR_AP, VIKING_LANDED,
														DRONE, ZERGLING, BANELING, ULTRALISK, BROODLING };

const std::vector<UNIT_TYPEID> PROJECTILE_UNIT_TYPES = { STALKER, ADEPT, HIGH_TEMPLAR, PHOENIX, TEMPEST,
														MARAUDER, VIKING, LIBERATOR, BANSHEE, BATTLECRUISER,
														QUEEN, ROACH, HYDRA, LURKER, MUTALISK, CORRUPTER, BROOD_LORD, LOCUST };
const std::vector<UNIT_TYPEID> TOWNHALL_TYPES = { COMMAND_CENTER, COMMAND_CENTER_FLYING, ORBITAL, ORBITAL_FLYING, PLANETARY, NEXUS, HATCHERY, LAIR, HIVE };


const std::vector<UNIT_TYPEID> VESPENE_GEYSER_TYPES = { UNIT_TYPEID::NEUTRAL_PROTOSSVESPENEGEYSER, UNIT_TYPEID::NEUTRAL_PURIFIERVESPENEGEYSER, UNIT_TYPEID::NEUTRAL_RICHVESPENEGEYSER, UNIT_TYPEID::NEUTRAL_SHAKURASVESPENEGEYSER, UNIT_TYPEID::NEUTRAL_SPACEPLATFORMGEYSER, UNIT_TYPEID::NEUTRAL_VESPENEGEYSER };


const std::vector<UNIT_TYPEID> MINERAL_PATCH = {	UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD, 
													UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD750, 
													UNIT_TYPEID::NEUTRAL_LABMINERALFIELD,
													UNIT_TYPEID::NEUTRAL_LABMINERALFIELD750, 
													UNIT_TYPEID::NEUTRAL_MINERALFIELD, 
													UNIT_TYPEID::NEUTRAL_MINERALFIELD450, 
													UNIT_TYPEID::NEUTRAL_MINERALFIELD750,
													UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD, 
													UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD750, 
													UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD,
													UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD750, 
													UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD, 
													UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD750 };

enum UpgradeType
{
	ground_weapons,
	ground_armor,
	shields,
	air_weapons,
	air_armor
};

enum AttackPath
{
	direct,
	indirect,
	alt
};

struct ScoutInfoZerg
{
	float natural_timing = 0;
	float third_timing = 0;
	float gas_timing = 0;
	int gas_mined = 0;
	float pool_timing = 0;
	bool pool_active = 0;
	int drone_count = 0;
	float roach_warren_timing = 0;
};

enum FirstRaxProduction {
	idle,
	marine,
	reaper,
	reactor,
	techlab
};

struct ScoutInfoTerran
{
	float natural_timing = 0;
	float third_timing = 0;
	float gas_timing = 0;
	Point3D gas_pos;
	float second_gas_timing = 0;
	int gas_mined = 0;
	float barrackes_timing = 0;
	bool factory_timing = 0;
	int scv_count = 0;
	int num_barracks = 0;
	FirstRaxProduction first_rax_production = FirstRaxProduction::idle;
};

struct WarpgateStatus
{
	bool used;
	uint32_t frame_ready;
	WarpgateStatus() 
	{
		used= false;
		frame_ready = 0;
	}
	WarpgateStatus(int curr_frame)
	{
		used = false;
		frame_ready = curr_frame + 1;
	}
};

struct UnitCost
{
	int mineral_cost = 0;
	int vespene_cost = 0;
	float supply = 0;
	UnitCost() {};
	UnitCost(int x, int y, float z)
	{
		mineral_cost = x;
		vespene_cost = y;
		supply = z;
	}
	UnitCost operator+(const UnitCost& other) const
	{
		return UnitCost(mineral_cost + other.mineral_cost, vespene_cost + other.vespene_cost, supply + other.supply);
	}
	UnitCost operator-(const UnitCost& other) const
	{
		return UnitCost(mineral_cost - other.mineral_cost, vespene_cost - other.vespene_cost, supply - other.supply);
	}
	void operator+=(const UnitCost& other) 
	{
		mineral_cost += other.mineral_cost;
		vespene_cost += other.vespene_cost;
		supply += other.supply;
	}
	void operator-=(const UnitCost& other)
	{
		mineral_cost -= other.mineral_cost;
		vespene_cost -= other.vespene_cost;
		supply -= other.supply;
	}
	UnitCost operator*(const int num) const
	{
		return UnitCost(mineral_cost * num, vespene_cost * num, supply * num);
	}
	UnitCost operator/(const float num) const
	{
		return UnitCost(mineral_cost / num, vespene_cost / num, supply / num);
	}
	bool operator==(const UnitCost& rhs) const
	{
		return (mineral_cost == rhs.mineral_cost &&
			vespene_cost == rhs.vespene_cost &&
			supply == rhs.supply);
	}
#pragma warning(push)
#pragma warning(disable : 4244)
	void operator/=(const float num)
	{
		mineral_cost /= num;
		vespene_cost /= num;
		supply /= num;
	}
#pragma warning(pop)
	std::string toString() const
	{
		return "minerals-" + std::to_string(mineral_cost) + ", vespene-" + std::to_string(vespene_cost) + ", supply-" + std::to_string(supply);
	}
};

struct EnemyUnitPosition
{
	Point2D pos;
	int frames;
	EnemyUnitPosition()
	{
		pos = Point2D(0, 0);
		frames = 0;
	}
	EnemyUnitPosition(Point2D pos)
	{
		this->pos = pos;
		frames = 0;
	}
};

enum class TryActionResult
{
	success,
	probe_not_in_range,
	invalid_position,
	low_tech,
	cannot_afford,
	unpowered,
	busy,
	invalid_parameter
};

enum class GameStateWorker
{
	even,
	slightly_less,
	slightly_more,
	much_less,
	much_more
};

struct GameState
{
	GameStateWorker game_state_worker = GameStateWorker::even;
	bool good_worker_intel = false;
};

enum class CommandPriorty
{
	low,
	normal,
	high,
	max
};

enum class PathDirection
{
	none,
	forward,
	backward
};

struct EnemyAttack
{
	const Unit* unit;
	uint32_t impact_frame;
	EnemyAttack(const Unit* unit, int impact_frame)
	{
		this->unit = unit;
		this->impact_frame = impact_frame;
	}
};

struct LiberatorZone
{
	Point2D pos;
	bool current;
	LiberatorZone(Point2D pos)
	{
		this->pos = pos;
		current = true;
	}
	bool operator==(const LiberatorZone& b)
	{
		return pos == b.pos;
	}
};

struct EnemyArmyGroup
{
	Units units;
	Point2D current_pos;
	Point2D attack_pos;
	std::vector<Point2D> attack_path;
	EnemyArmyGroup(Units units, Point2D current_pos, Point2D attack_pos, std::vector<Point2D> attack_path)
	{
		this->units = units;
		this->current_pos = current_pos;
		this->attack_pos = attack_pos;
		this->attack_path = attack_path;
	}
};

struct DefensiveGroup
{
	Point2D defensive_pos;
	Units friendly_units;
	Units enemy_units;
	float status = 0;
	DefensiveGroup(Point2D defensive_pos, Units friendly_units, Units enemy_units)
	{
		this->defensive_pos = defensive_pos;
		this->friendly_units = friendly_units;
		this->enemy_units = enemy_units;
	}
};

}